train_data_dir: "/home/nuna_hadzic1/spectrograms150/training"
validation_data_dir: "/home/nuna_hadzic1/spectrograms150/validation"
test_data_dir: "/home/nuna_hadzic1/spectrograms150/testing"

# train_data_dir: "/media/bro/New Volume/subsetorgspectograms150/training"
# validation_data_dir: "/media/bro/New Volume/subsetorgspectograms150/validation"
# test_data_dir: "/media/bro/New Volume/subsetorgspectograms150/testing"

model: "inception_resnet_v2_crnn"
gpus: 2

batch_size: 256
learning_rate: 0.001
num_epochs: 50

input_shape: [129, 150, 1]
pixel_per_second: 50

num_classes: 3
label_names: ["croatian", "french", "spanish"]