# folder locations for training, validation and testing sets
train_data_dir: "/home/user/spectrograms/training"
validation_data_dir: "/home/user/spectrograms/validation"
test_data_dir: "/home/user/spectrograms/testing"


model: "inception_resnet_v2_crnn"
gpus: 2

batch_size: 256
learning_rate: 0.001
num_epochs: 50

input_shape: [129, 150, 1]
pixel_per_second: 50

num_classes: 3
label_names: ["croatian", "french", "spanish"]